import { randomUUID } from 'node:crypto';

import { OrderDto, RestaurantDto, UserDto } from '@/api';

export const person: UserDto[] = [
  {
    id: randomUUID(),
    name: 'John Doe',
    email: 'john1@doe.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/men/1.jpg',
    phone: '+3620111222',
    addresses: ['1010 Budapest, Kossuth Lajos utca 1.'],
  },
  {
    id: randomUUID(),
    name: 'Jane Smith',
    email: 'jane2@smith.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/women/2.jpg',
    phone: '+3620111223',
    addresses: ['1051 Budapest, Váci utca 2.'],
  },
  {
    id: randomUUID(),
    name: 'David Johnson',
    email: 'david3@johnson.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/men/3.jpg',
    phone: '+3620111224',
    addresses: ['1061 Budapest, Andrássy út 3.'],
  },
  {
    id: randomUUID(),
    name: 'Emily Davis',
    email: 'emily4@davis.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/women/4.jpg',
    phone: '+3620111225',
    addresses: ['1072 Budapest, Király utca 4.'],
  },
  {
    id: randomUUID(),
    name: 'Michael Brown',
    email: 'michael5@brown.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/men/5.jpg',
    phone: '+3620111226',
    addresses: ['1085 Budapest, Rákóczi út 5.'],
  },
  {
    id: randomUUID(),
    name: 'Sophia Wilson',
    email: 'sophia6@wilson.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/women/6.jpg',
    phone: '+3620111227',
    addresses: ['1094 Budapest, Tompa utca 6.'],
  },
  {
    id: randomUUID(),
    name: 'James Taylor',
    email: 'james7@taylor.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/men/7.jpg',
    phone: '+3620111228',
    addresses: ['1106 Budapest, Jászberényi út 7.'],
  },
  {
    id: randomUUID(),
    name: 'Olivia Martinez',
    email: 'olivia8@martinez.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/women/8.jpg',
    phone: '+3620111229',
    addresses: ['1113 Budapest, Villányi út 8.'],
  },
  {
    id: randomUUID(),
    name: 'Benjamin Lee',
    email: 'benjamin9@lee.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
    phone: '+3620111230',
    addresses: ['1126 Budapest, Márvány utca 9.'],
  },
  {
    id: randomUUID(),
    name: 'Amelia Gonzalez',
    email: 'amelia10@gonzalez.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/women/10.jpg',
    phone: '+3620111231',
    addresses: ['1139 Budapest, Váci út 10.'],
  },
  {
    id: randomUUID(),
    name: 'William Harris',
    email: 'william11@harris.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
    phone: '+3620111232',
    addresses: ['1146 Budapest, Dózsa György út 11.'],
  },
  {
    id: randomUUID(),
    name: 'Isabella Clark',
    email: 'isabella12@clark.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/women/12.jpg',
    phone: '+3620111233',
    addresses: ['1151 Budapest, Fő út 12.'],
  },
  {
    id: randomUUID(),
    name: 'Henry Robinson',
    email: 'henry13@robinson.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/men/13.jpg',
    phone: '+3620111234',
    addresses: ['1163 Budapest, Veres Péter út 13.'],
  },
  {
    id: randomUUID(),
    name: 'Mia Rodriguez',
    email: 'mia14@rodriguez.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/women/14.jpg',
    phone: '+3620111235',
    addresses: ['1172 Budapest, Pesti út 14.'],
  },
  {
    id: randomUUID(),
    name: 'Alexander Lewis',
    email: 'alexander15@lewis.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/men/15.jpg',
    phone: '+3620111236',
    addresses: ['1183 Budapest, Üllői út 15.'],
  },
  {
    id: randomUUID(),
    name: 'Charlotte Walker',
    email: 'charlotte16@walker.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/women/16.jpg',
    phone: '+3620111237',
    addresses: ['1191 Budapest, Ady Endre út 16.'],
  },
  {
    id: randomUUID(),
    name: 'Daniel Hall',
    email: 'daniel17@hall.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/men/17.jpg',
    phone: '+3620111238',
    addresses: ['1204 Budapest, Nagykőrösi út 17.'],
  },
  {
    id: randomUUID(),
    name: 'Grace Allen',
    email: 'grace18@allen.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/women/18.jpg',
    phone: '+3620111239',
    addresses: ['1211 Budapest, Kossuth Lajos utca 18.'],
  },
  {
    id: randomUUID(),
    name: 'Matthew Young',
    email: 'matthew19@young.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/men/19.jpg',
    phone: '+3620111240',
    addresses: ['1222 Budapest, Leányka utca 19.'],
  },
  {
    id: randomUUID(),
    name: 'Ava King',
    email: 'ava20@king.com',
    role: 'CUSTOMER',
    image: 'https://randomuser.me/api/portraits/women/20.jpg',
    phone: '+3620111241',
    addresses: ['1239 Budapest, Grassalkovich út 20.'],
  },
];

export const order: OrderDto[] = [
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 1500,
    status: 'PENDING',
    createdAt: '2021-08-26T12:00:00.000Z',
    items: [
      {
        id: randomUUID(),
        foodId: randomUUID(),
        orderId: randomUUID(),
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 2300,
    status: 'FINISHED',
    createdAt: '2021-08-26T12:15:00.000Z',
    items: [
      {
        id: '2',
        foodId: '2',
        orderId: '2',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 1800,
    status: 'CANCELLED',
    createdAt: '2021-08-26T12:30:00.000Z',
    items: [
      {
        id: '3',
        foodId: '3',
        orderId: '3',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 2500,
    status: 'ONGOING',
    createdAt: '2021-08-26T12:45:00.000Z',
    items: [
      {
        id: '4',
        foodId: '4',
        orderId: '4',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 1900,
    status: 'PENDING',
    createdAt: '2021-08-26T13:00:00.000Z',
    items: [
      {
        id: '5',
        foodId: '5',
        orderId: '5',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 3200,
    status: 'FINISHED',
    createdAt: '2021-08-26T13:15:00.000Z',
    items: [
      {
        id: '6',
        foodId: '6',
        orderId: '6',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 1100,
    status: 'ONGOING',
    createdAt: '2021-08-26T13:30:00.000Z',
    items: [
      {
        id: '7',
        foodId: '7',
        orderId: '7',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 2200,
    status: 'CANCELLED',
    createdAt: '2021-08-26T13:45:00.000Z',
    items: [
      {
        id: '8',
        foodId: '8',
        orderId: '8',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 2800,
    status: 'PENDING',
    createdAt: '2021-08-26T14:00:00.000Z',
    items: [
      {
        id: '9',
        foodId: '9',
        orderId: '9',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 1700,
    status: 'FINISHED',
    createdAt: '2021-08-26T14:15:00.000Z',
    items: [
      {
        id: '10',
        foodId: '10',
        orderId: '10',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 2400,
    status: 'CANCELLED',
    createdAt: '2021-08-26T14:30:00.000Z',
    items: [
      {
        id: '11',
        foodId: '11',
        orderId: '11',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 1500,
    status: 'ONGOING',
    createdAt: '2021-08-26T14:45:00.000Z',
    items: [
      {
        id: '12',
        foodId: '12',
        orderId: '12',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 3300,
    status: 'PENDING',
    createdAt: '2021-08-26T15:00:00.000Z',
    items: [
      {
        id: '13',
        foodId: '13',
        orderId: '13',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 2900,
    status: 'FINISHED',
    createdAt: '2021-08-26T15:15:00.000Z',
    items: [
      {
        id: '14',
        foodId: '14',
        orderId: '14',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 1700,
    status: 'ONGOING',
    createdAt: '2021-08-26T15:30:00.000Z',
    items: [
      {
        id: '15',
        foodId: '15',
        orderId: '15',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 1600,
    status: 'CANCELLED',
    createdAt: '2021-08-26T15:45:00.000Z',
    items: [
      {
        id: '16',
        foodId: '16',
        orderId: '16',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 2100,
    status: 'PENDING',
    createdAt: '2021-08-26T16:00:00.000Z',
    items: [
      {
        id: '17',
        foodId: '17',
        orderId: '17',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 1200,
    status: 'FINISHED',
    createdAt: '2021-08-26T16:15:00.000Z',
    items: [
      {
        id: '18',
        foodId: '18',
        orderId: '18',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 3100,
    status: 'ONGOING',
    createdAt: '2021-08-26T16:30:00.000Z',
    items: [
      {
        id: '19',
        foodId: '19',
        orderId: '19',
      },
    ],
  },
  {
    id: randomUUID(),
    userId: randomUUID(),
    restaurantId: randomUUID(),
    total: 1800,
    status: 'CANCELLED',
    createdAt: '2021-08-26T16:45:00.000Z',
    items: [
      {
        id: '20',
        foodId: '20',
        orderId: '20',
      },
    ],
  },
];

export const restaurant: RestaurantDto[] = [
  {
    id: randomUUID(),
    name: 'Pizza Place',
    description: 'The best pizza place in town',
    addresses: ['Bp utca 1.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Burger House',
    description: 'The best burger place in town',
    addresses: ['Bp utca 2.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Sushi Bar',
    description: 'The best sushi place in town',
    addresses: ['Bp utca 3.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Pasta House',
    description: 'The best pasta place in town',
    addresses: ['Bp utca 4.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Kebab House',
    description: 'The best kebab place in town',
    addresses: ['Bp utca 5.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Coffee Shop',
    description: 'The best coffee place in town',
    addresses: ['Bp utca 6.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Ice Cream Shop',
    description: 'The best ice cream place in town',
    addresses: ['Bp utca 7.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Donut Shop',
    description: 'The best donut place in town',
    addresses: ['Bp utca 8.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Bakery',
    description: 'The best bakery in town',
    addresses: ['Bp utca 9.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Bar',
    description: 'The best bar in town',
    addresses: ['Bp utca 10.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Pub',
    description: 'The best pub in town',
    addresses: ['Bp utca 11.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Restaurant',
    description: 'The best restaurant in town',
    addresses: ['Bp utca 12.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Cafe',
    description: 'The best cafe in town',
    addresses: ['Bp utca 13.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Diner',
    description: 'The best diner in town',
    addresses: ['Bp utca 14.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Fast Food',
    description: 'The best fast food place in town',
    addresses: ['Bp utca 15.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Food Truck',
    description: 'The best food truck in town',
    addresses: ['Bp utca 16.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Buffet',
    description: 'The best buffet in town',
    addresses: ['Bp utca 17.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Bistro',
    description: 'The best bistro in town',
    addresses: ['Bp utca 18.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Steakhouse',
    description: 'The best steakhouse in town',
    addresses: ['Bp utca 19.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
  {
    id: randomUUID(),
    name: 'Tavern',
    description: 'The best tavern in town',
    addresses: ['Bp utca 20.'],
    rating: [4.5],
    tags: ['ITALIAN', 'PIZZA'],
    image: 'https://foodish-api.com/images/pizza/pizza1.jpg',
    ownerId: randomUUID(),
  },
];
