-- CreateEnum
CREATE TYPE "Tag" AS ENUM ('BURGER', 'AMERICAN', 'PIZZA', 'SALAD', 'ITALIAN', 'CHICKEN', 'BREAKFAST', 'PASTA', 'ASIAN', 'VEGETARIAN', 'VEGAN', 'SOUP', 'GYROS', 'STREET', 'DESSERT', 'THAI', 'KEBAB', 'SANDWICH', 'JAPANESE', 'MEDITERANEAN', 'MEXICAN', 'SUSHI');

-- AlterTable
ALTER TABLE "Restaurant" ADD COLUMN     "tags" "Tag"[];
