/**
 * Dine and Dash
 * Api description for Dine and Dash full stack food delivery application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartItemDto } from './cartItemDto';


export interface CartDto { 
    id: string;
    userId: string;
    total: number;
    items?: Array<CartItemDto>;
}

