/**
 * Dine and Dash
 * Api description for Dine and Dash full stack food delivery application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemDto } from './orderItemDto';


export interface OrderDto { 
    id: string;
    userId: string;
    restaurantId: string;
    total: number;
    status: OrderDto.StatusEnum;
    createdAt: string;
    items?: Array<OrderItemDto>;
}
export namespace OrderDto {
    export type StatusEnum = 'PENDING' | 'ONGOING' | 'FINISHED' | 'CANCELLED';
    export const StatusEnum = {
        Pending: 'PENDING' as StatusEnum,
        Ongoing: 'ONGOING' as StatusEnum,
        Finished: 'FINISHED' as StatusEnum,
        Cancelled: 'CANCELLED' as StatusEnum
    };
}


