/**
 * Dine and Dash
 * Api description for Dine and Dash full stack food delivery application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestaurantDto } from './restaurantDto';
import { CartDto } from './cartDto';


export interface UserDto { 
    id: string;
    name: string;
    email: string;
    phone: string;
    addresses: Array<string>;
    role: UserDto.RoleEnum;
    ownerOf?: RestaurantDto;
    image: string;
    cart?: CartDto;
}
export namespace UserDto {
    export type RoleEnum = 'ADMIN' | 'CUSTOMER' | 'COURIER' | 'OWNER';
    export const RoleEnum = {
        Admin: 'ADMIN' as RoleEnum,
        Customer: 'CUSTOMER' as RoleEnum,
        Courier: 'COURIER' as RoleEnum,
        Owner: 'OWNER' as RoleEnum
    };
}


